name: Percy
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag testrun .
      - name: Run server with Docker
        run: docker run -p ${PORT}:80 testrun &
      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          command: 'node snapshots.js'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
