name: Percy
on:
  push:
    branches: [master]
  pull_request:

env:
  PORT: 8765

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag testrun .
      - name: Run server with Docker
        run: docker run -p ${PORT}:80 testrun &
      - name: Snapshot screenshots for Percy
        uses: percy/exec-action@v0.3.0
        with:
          command: 'node snapshots.js'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
